language: python
cache: pip
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install pipenv
    - pipenv install --deploy --dev
script:
    - pipenv run isort --recursive --diff .
    - pipenv run black --check .
    - pipenv run flake8
    - pipenv run mypy
    - pipenv run pytest --cov --cov-fail-under=100
